version: '3' # Версия указывает на версию синтаксиса
# Лучше использовать актуальную версию, которая рекомендуется в документации
services:

  redis:
    image: redis
    ports:
      - '6379:6379'

  db:
    image: postgres
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=password
#      - POSTGRES_DB=postgres
#      - POSTGRES_POST=
#      - POSTGRES_HOST=
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    env_file:
      - .env
    build: .
    tty: true
    command: >
      bash -c "python manage.py makemigrations
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - '8001:8000'
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  celery:
    build: .
    tty: true
    env_file:
      - .env
    command: >
      bash -c "celery -A config worker --beat -l INFO"
    depends_on:
      - redis
      - app
    links:
      - redis

#  celery_beat:
#    build: .
#    tty: true
#    command: celery -A config beat -l INFO -S django
#    depends_on:
#      - redis
#      - app